### ISSUE TITLE
DownloadFatal when downloading specific link

### ISSUE THREAD

**Issue by davinkevin** [axet/vget#70] opened 2016-12-10 21:14 UTC
Hi, 

I find a problem with this link : https://www.youtube.com/watch?v=aJIMoLgqU_o

I have the following error when trying to download
```
2016-12-10 22:07:35.987 DEBUG 31091 --- [Downloader-1] l.d.p.m.w.downloader.AbstractDownloader  : Run
2016-12-10 22:07:36.011 DEBUG 31091 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Download
2016-12-10 22:07:37.625 DEBUG 31091 --- [Downloader-1] p.m.w.d.YoutubeDownloader$YoutubeWatcher : watch?v=aJIMoLgqU_o EXTRACTING_DONE
2016-12-10 22:07:37.710 ERROR 31091 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Third part Exception :

com.github.axet.vget.ex.DownloadFatal: null
	at com.github.axet.vget.VGet.download(VGet.java:642) ~[vget-1.2.2.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.YoutubeDownloader.download(YoutubeDownloader.java:83) ~[classes!/:1.1.0-SNAPSHOT]
	at javaslang.control.Try.of(Try.java:42) ~[javaslang-2.0.2.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.startDownload(AbstractDownloader.java:65) ~[classes!/:1.1.0-SNAPSHOT]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.run(AbstractDownloader.java:56) ~[classes!/:1.1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at com.sun.proxy.$Proxy150.run(Unknown Source) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

I'm working with the last version of Vget and the error is linked to https://github.com/axet/vget/blob/master/src/main/java/com/github/axet/vget/VGet.java#L642

Could we have a better error message and could you help me to solve this issue ?

Thanks

**Comment by axet** [comment] 2016-12-10 21:31
This is new feature: stop retrying when reaching retrying limit (5 retires).

It is very strange error, seems like internal problem. Instead of reporting exception cause it shows null. Seems like exception was cleared after DownloadFatal was thrown.

Video works fine on my machine and I having trouble undesranding why. Do you clear any exception in your code for VideoDownloadInfo?

**Comment by davinkevin** [comment] 2016-12-10 22:07
> This is new feature: stop retrying when reaching retrying limit (5 retires).

I don't retry myself, I always rely on the Vget system

> It is very strange error, seems like internal problem. Instead of reporting exception cause it shows null. Seems like exception was cleared after DownloadFatal was thrown.

I've dig into the error, and this is normal the DownloadFatal show the message null, it's because the `printStackTrace` is not called when used in a logger (SLF4J in my case). It only use the `getStackTrace` and `getMessage` method of type `Throwable`.
So, it seems DownloadFatal created with `VideoFileInfo` and `List<VideoFileInfo>` never works with standard loggers...

To solve that, you should generate the error message during the construction of the error instead of on the `printStackTrace` method.

I've hijacked the printstacktrace to get the string which should be printed, I found that : 

```
2016-12-10 22:53:45.276 ERROR 31833 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Message : java.lang.NullPointerException
	at com.github.axet.wget.DirectRange.downloadPart(DirectRange.java:33)
	at com.github.axet.wget.DirectRange$1.download(DirectRange.java:103)
	at com.github.axet.wget.RetryWrap$1.download(RetryWrap.java:152)
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:88)
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:182)
	at com.github.axet.wget.DirectRange.download(DirectRange.java:83)
	at com.github.axet.vget.VGet$5.run(VGet.java:598)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at com.github.axet.wget.DirectRange.downloadPart(DirectRange.java:33)
	at com.github.axet.wget.DirectRange$1.download(DirectRange.java:103)
	at com.github.axet.wget.RetryWrap$1.download(RetryWrap.java:152)
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:88)
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:182)
	at com.github.axet.wget.DirectRange.download(DirectRange.java:83)
	at com.github.axet.vget.VGet$5.run(VGet.java:598)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
com.github.axet.vget.ex.DownloadFatal
	at com.github.axet.vget.VGet.download(VGet.java:642)
	at lan.dk.podcastserver.manager.worker.downloader.YoutubeDownloader.download(YoutubeDownloader.java:87)
	at javaslang.control.Try.of(Try.java:42)
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.startDownload(AbstractDownloader.java:65)
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.run(AbstractDownloader.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy150.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

> Video works fine on my machine and I having trouble undesranding why it crashes. Do you clear any exceptions in your code for VideoFileInfo?

The video works on my dev computer (MacOS Java 1.8.0.112) and not on my Server (Debian, Java 1.8.0.101). Both computers are on the same network.

**Comment by axet** [comment] 2016-12-10 22:21
1) Seems like exception is not serialised properly. Not sure what is wrong here.

2) NullPointerException can be raised only if target file is null, It is not possible because of VGet checks this:

                        if (dinfo.targetFile == null) {
                            throw new RuntimeException("bad target");
                        }

Can you clarify on those?

**Comment by davinkevin** [comment] 2016-12-11 11:43
Same thing with v1.2.3

```
2016-12-11 12:31:18.608 ERROR 8192 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Third part Exception :

com.github.axet.vget.ex.DownloadFatal: null
	at com.github.axet.vget.VGet.download(VGet.java:641) ~[vget-1.2.3.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.YoutubeDownloader.download(YoutubeDownloader.java:83) ~[classes!/:1.1.0-SNAPSHOT]
	at javaslang.control.Try.of(Try.java:42) ~[javaslang-2.0.2.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.startDownload(AbstractDownloader.java:65) ~[classes!/:1.1.0-SNAPSHOT]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.run(AbstractDownloader.java:56) ~[classes!/:1.1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at com.sun.proxy.$Proxy150.run(Unknown Source) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

I can't dig into the code, because I can't have the debug mode from my prod env (remote and in a container...).

> Seems like exception is not serialised properly. Not sure what is wrong here. (it seems VideoFileInfo missing Serialization implementation, I'll reupload)

I don't think so, there is no serialisation, it's juste the logger calling the `getStackTrace` which return null because the `DownloadFatal.class` isn't a correct `Throwable.class` => See my previous message.

I will try to fork the project and use a SNAPSHOT with customisation in order to find the root of this bug. 

The last error I have posted show that the method `DirectRange::downloadPart` (`DirectRange.java:33`) throw a NPE, so the line 
```
info.setCount(FileUtils.sizeOf(f));
```
is the source of the problem, the info seems to be null.

**Comment by axet** [comment] 2016-12-11 11:52
1) What do you mean 'not correct Throwable'? What is correct one?

2) Lines are changed, your stack trace for previous version of library. It points to 'if (!f.exists())'

**Comment by davinkevin** [comment] 2016-12-11 12:17
> What do you mean 'not correct Throwable'? What is correct one?

Like I've already said in this issue, the method `getStackTrace` and `getMessage` use internal value never populated by `DownloadFatal` implementation when construct from with `VideoFileInfo` and `List<VideoFileInfo>`. The override method `printStackTrace` are never called from a Logger implementation (in my case SLF4J).

 > Lines are changed, your stack trace for previous version of library. It points to 'if (!f.exists())'. And 'target' can not be null!

The error line was 642 in v1.2.2 and 641 in v1.2.3 which is are the same in term of implementation, they are both leading to this : 
![image](https://cloud.githubusercontent.com/assets/1970922/21079986/8a22d67c-bfa3-11e6-9911-af0d9ad9b30a.png)

In v1.2.3 : https://github.com/axet/vget/blob/master/src/main/java/com/github/axet/vget/VGet.java#L641

In v1.2.2 : 
https://github.com/axet/vget/blob/1772d0eea74a04a33af808b7ecbed41ec0872b63/src/main/java/com/github/axet/vget/VGet.java#L642

I compare to my first message, not the one where I hijacked the DownloadFatal value to get the inner value of each VideoFileInfo exception. Inside this, the result is the same between 1.2.2 and 1.2.3

**Comment by axet** [comment] 2016-12-11 12:21
I update my last comment.

1) Exception is correct, but has to be handled manually

2) I'm speaking about wget library, which has been updated as well.

**Comment by davinkevin** [comment] 2016-12-11 15:41
> Exception is correct, but has to be handled manually

If it's correct, why it's not working as any other exception in a logger ? I don't think handling the exception in my business code is the right way to do it, it should be done by the vget / wget lib.

By the way, what do you want me to do to handle it ? Could you be less brief in your answer, by adding code example or extra information ? Thanks

> I'm speaking about wget library, which has been updated as well.

Ok, but It's a dependency of Vget, so I don't use it directly... The error shown when I hijacked the Exception expose a problem inside Wget, but it's the same after the update of vget (to 1.2.3).

And, BTW, could you release SNAPSHOT version of the lib instead upgrading it ? For people using it, it very confusing to see N version just because we try to solve a bug in the lib.

Thanks

**Comment by axet** [comment] 2016-12-11 15:48
1) DownloadFatal - multithread exception, can hold multiple expections from multiple threads (wget/vget - multithread libraires). When exceptions occurs they been packed into DownloadFatal. To see what happens inside library and exact error it is necessary to unfold this error. Or simply call printStackTrace. Every DownloadFatal can hold multiple DownloadMultiTask exceptions which can hold multiple Part exceptions. Think of it like vget API.

2) The NullPointerException - can't happens, something is going wrong here. After you unfold DownloadFatal into several exceptions we gonna see what exactly.

3) We can use dev version while debugging the library. Since almost nothing happening and for most part we are fixing bugs adding few 0.0.X numbers alright.

**Comment by davinkevin** [comment] 2016-12-11 16:18
Same result as before : 

```
2016-12-11 17:13:42.272 ERROR 11760 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Third part Exception :

com.github.axet.vget.ex.DownloadFatal: null
	at com.github.axet.vget.VGet.download(VGet.java:641) ~[vget-1.2.3.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.YoutubeDownloader.download(YoutubeDownloader.java:84) ~[classes!/:1.1.0-SNAPSHOT]
	at javaslang.control.Try.of(Try.java:42) ~[javaslang-2.0.2.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.startDownload(AbstractDownloader.java:65) ~[classes!/:1.1.0-SNAPSHOT]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.run(AbstractDownloader.java:56) ~[classes!/:1.1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at com.sun.proxy.$Proxy150.run(Unknown Source) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]

2016-12-11 17:13:42.279 ERROR 11760 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Error in vget :

java.lang.NullPointerException: null
	at com.github.axet.wget.DirectRange.downloadPart(DirectRange.java:31) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange$1.download(DirectRange.java:101) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap$1.download(RetryWrap.java:152) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:88) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:182) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange.download(DirectRange.java:81) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.vget.VGet$5.run(VGet.java:598) ~[vget-1.2.3.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

2016-12-11 17:13:42.279 ERROR 11760 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Error in vget :

java.lang.NullPointerException: null
	at com.github.axet.wget.DirectRange.downloadPart(DirectRange.java:31) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange$1.download(DirectRange.java:101) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap$1.download(RetryWrap.java:152) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:88) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:182) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange.download(DirectRange.java:81) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.vget.VGet$5.run(VGet.java:598) ~[vget-1.2.3.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

To produce this error, I have this element in my code : 

```java
try {
            VGetParser parser = wGetFactory.parser(item.getUrl());
            v = wGetFactory.newVGet(parser.info(new URL(item.getUrl())));

            v.extract(parser, stopDownloading, watcher);

            v
                .getVideo()
                .getInfo()
                .forEach(vi -> vi.targetFile = generatePartFile(getTargetFile(item, v.getVideo().getTitle()), vi).toFile());

            v.download(parser, stopDownloading, watcher);
        } catch (DownloadMultipartError e) {
            /* Ignored for brevity */
        } catch (DownloadInterruptedError e) {
            /* Ignored for brevity */
        } catch (StringIndexOutOfBoundsException | MalformedURLException | NullPointerException | DownloadError e) {
            log.error("Third part Exception : ", e);

            if (DownloadFatal.class.isInstance(e)) {
                DownloadFatal.class.cast(e).list
                    .stream()
                    .map(URLInfo::getException)
                    .filter(Objects::nonNull)
                    .forEach(exception -> log.error("Error in vget : ", exception));
            }

            /* Ignored for brevity */
        }
```

Do you have any idea ?

**Comment by axet** [comment] 2016-12-11 16:35
As you can see NullPointerException can occur only if 'target == null':

https://github.com/axet/wget/blob/master/src/main/java/com/github/axet/wget/DirectRange.java#L31

Can you check your code is produce correct targetFile?

```java
 v
                .getVideo()
                .getInfo()
                .forEach(vi -> vi.targetFile = generatePartFile(getTargetFile(item, v.getVideo().getTitle()), vi).toFile());
```

**Comment by axet** [comment] 2016-12-11 16:36
And please use -dev versions of vget && wget (update vget/pom.xml to switch to wget-SNAPSHOT)

**Comment by davinkevin** [comment] 2016-12-11 17:20
This code can't produce a NPE, because I'm calling the method `Path::toFile` on the result of `generatePartFile(getTargetFile(item, v.getVideo().getTitle()), vi)`, so if a null appears here, a NPE should be raised before... 

I've updated the repository to have the Snapshot version, my maven repo is updating... 

I will post as soon as I have a new stack-trace / information (it require me to re-install the app every time... from the commit to the deployment from the CI, it can take few minutes...)

**Comment by davinkevin** [comment] 2016-12-11 18:08
After 400 mo of maven update... the system doesn't find the JAR... 

https://github.com/davinkevin/Podcast-Server/blob/vgetbug/Backend/pom.xml

Do I miss something in the configuration to use dev version ?

**Comment by axet** [comment] 2016-12-11 18:27
1) what if getTitle() return null?

2) 'dev' version should not be get by maven but from git. git checkout dev && mvn install

**Comment by davinkevin** [comment] 2016-12-11 18:51
The method `generatePartFile(getTargetFile(item, v.getVideo().getTitle()), vi)` return null or Paths, so whatever `v.getVideo().getTitle()` return, NPE should happen before...

It's building, I have to bypass the CI to deploy, so it's not as simple as usual ;)

**Comment by davinkevin** [comment] 2016-12-11 19:00
Same thing here...

```
2016-12-11 19:57:29.939 DEBUG 13870 --- [Downloader-1] p.m.w.d.YoutubeDownloader$YoutubeWatcher : watch?v=aJIMoLgqU_o EXTRACTING_DONE
2016-12-11 19:57:29.977  INFO 13870 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : vi.targetFile : /shares/podcast/NG - BE/Igor_Minar_-_Opening_Keynote_NG-BE_2016.psdownload.video.mp4
2016-12-11 19:57:29.977  INFO 13870 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : vi.targetFile : /shares/podcast/NG - BE/Igor_Minar_-_Opening_Keynote_NG-BE_2016.psdownload.audio.webm
2016-12-11 19:57:30.065 ERROR 13870 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Third part Exception :

com.github.axet.vget.ex.DownloadFatal: java.lang.InterruptedException
	at com.github.axet.vget.VGet.download(VGet.java:644) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.YoutubeDownloader.download(YoutubeDownloader.java:87) ~[classes!/:1.1.0-SNAPSHOT]
	at javaslang.control.Try.of(Try.java:42) ~[javaslang-2.0.2.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.startDownload(AbstractDownloader.java:65) ~[classes!/:1.1.0-SNAPSHOT]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.run(AbstractDownloader.java:56) ~[classes!/:1.1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at com.sun.proxy.$Proxy150.run(Unknown Source) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
Caused by: java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_101]
	at java.lang.Object.wait(Object.java:502) ~[na:1.8.0_101]
	at com.github.axet.threads.LimitThreadPool.waitUntilNextTaskEnds(LimitThreadPool.java:116) ~[threads-0.0.14.jar!/:na]
	at com.github.axet.threads.LimitThreadPool.waitUntilTermination(LimitThreadPool.java:130) ~[threads-0.0.14.jar!/:na]
	at com.github.axet.vget.VGet.download(VGet.java:628) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	... 14 common frames omitted

2016-12-11 19:57:30.070 ERROR 13870 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Error in vget :

java.lang.NullPointerException: null
	at com.github.axet.wget.DirectRange.downloadPart(DirectRange.java:31) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange$1.download(DirectRange.java:101) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap$1.download(RetryWrap.java:152) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:88) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:182) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange.download(DirectRange.java:81) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.vget.VGet$5.run(VGet.java:601) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

2016-12-11 19:57:30.073 ERROR 13870 --- [Downloader-1] l.d.p.m.w.downloader.YoutubeDownloader   : Error in vget :

java.lang.NullPointerException: null
	at com.github.axet.wget.DirectRange.downloadPart(DirectRange.java:31) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange$1.download(DirectRange.java:101) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap$1.download(RetryWrap.java:152) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:88) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:182) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.wget.DirectRange.download(DirectRange.java:81) ~[wget-1.4.2.jar!/:na]
	at com.github.axet.vget.VGet$5.run(VGet.java:601) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

I've print each targetFile too... 

The code executed is the following : 

```
try {
            VGetParser parser = wGetFactory.parser(item.getUrl());
            v = wGetFactory.newVGet(parser.info(new URL(item.getUrl())));

            v.extract(parser, stopDownloading, watcher);

            v
                .getVideo()
                .getInfo()
                .forEach(vi -> {
                    vi.targetFile = generatePartFile(getTargetFile(item, v.getVideo().getTitle()), vi).toFile();
                    log.info("vi.targetFile : {}", vi.targetFile);
                });

            v.download(parser, stopDownloading, watcher);
        } catch (DownloadMultipartError e) {
            /* Ignored for brevity */
        } catch (DownloadInterruptedError e) {
            /* Ignored for brevity */
        } catch (StringIndexOutOfBoundsException | MalformedURLException | NullPointerException | DownloadError e) {
            log.error("Third part Exception : ", e);

            if (DownloadFatal.class.isInstance(e)) {
                DownloadFatal.class.cast(e).list
                    .stream()
                    .map(URLInfo::getException)
                    .filter(Objects::nonNull)
                    .forEach(exception -> log.error("Error in vget : ", exception));
            }

            if (itemDownloadManager.canBeReset(item)) {
                log.info("Reset of Youtube download {}", item.getTitle());
                itemDownloadManager.resetDownload(item);
                return null;
            }
  /* Ignored for brevity */
        }
```

**Comment by axet** [comment] 2016-12-11 19:28
The problem is - you settings conflicting names for one download. Two files (audio + video) downloaded at the same location. I have fix for this. But your code, will fail anyway, since you expect downloaded to be in at different path check your generatePartFile.

You can pull && install

**Comment by davinkevin** [comment] 2016-12-11 19:32
The paths are different 

```
/shares/podcast/NG - BE/Igor_Minar_-_Opening_Keynote_NG-BE_2016.psdownload.video.mp4
/shares/podcast/NG - BE/Igor_Minar_-_Opening_Keynote_NG-BE_2016.psdownload.audio.webm
```

And BTW, the problem is mainly with this video, others work fine with the same logic and also from my Dev env... so I don't understand the `conflicting names`

I do a new install...

**Comment by davinkevin** [comment] 2016-12-11 19:59
So now, I have this error : 

```
java.lang.RuntimeException: Set download file or directory first
	at com.github.axet.vget.VGet.targetFileExt(VGet.java:319) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	at com.github.axet.vget.VGet.targetFile(VGet.java:357) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	at com.github.axet.vget.VGet.download(VGet.java:570) ~[vget-1.2.3-SNAPSHOT.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.YoutubeDownloader.download(YoutubeDownloader.java:87) ~[classes!/:1.1.0-SNAPSHOT]
	at javaslang.control.Try.of(Try.java:42) ~[javaslang-2.0.2.jar!/:na]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.startDownload(AbstractDownloader.java:65) [classes!/:1.1.0-SNAPSHOT]
	at lan.dk.podcastserver.manager.worker.downloader.AbstractDownloader.run(AbstractDownloader.java:56) [classes!/:1.1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at com.sun.proxy.$Proxy150.run(Unknown Source) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

I don't know what I can do to solve this as a vget user... I define correctly the TargetFile and the error says the opposite...

**Comment by axet** [comment] 2016-12-11 20:03
Try new fix.

**Comment by davinkevin** [comment] 2016-12-11 20:14
It's Working ! 

I still doesn't understand why I find a difference between my envs, but it's good to know this issue could be closed... When integrated in master branch ;)

Thanks for the help

**Closed** 2016-12-11 20:19 UTC
